import './globals.css'
import { Inter } from 'next/font/google'
import Layout from './components/Layout'
import { BiUpArrow } from 'react-icons/bi'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-black/40`} suppressHydrationWarning={true}>
        <Layout>
        <div className="fixed right-0 bottom-0 mb-3 mr-3">
        <BiUpArrow/>
      </div>
        {children}
        </Layout>
        </body>
    </html>
  )
}
